{"success": false, "error": "Traceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 544, in _run_solc\n    ret: Dict = json.loads(stdout)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 826, in main_impl\n    ) = process_all(filename, args, detector_classes, printer_classes)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 86, in process_all\n    compilations = compile_all(target, **vars(args))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 637, in compile_all\n    compilations.append(CryticCompile(target, **kwargs))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 117, in __init__\n    self._compile(**kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 548, in _compile\n    self._platform.compile(self, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 154, in compile\n    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 276, in _get_targets_json\n    return _run_solc(\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 548, in _run_solc\n    raise InvalidCompilation(f\"Invalid solc compilation {stderr}\")\ncrytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Multiple SPDX license identifiers found in source file. Use \"AND\" or \"OR\" to combine multiple licenses. Please see https://spdx.org for more information.\n--> /Users/giacomoibba/Desktop/SmarthER/mainnet/33/33cF1aA9541AdeBE6dAeFC3BcA342908b96C61e3_Controller.sol\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/IERC20.sol\" not found: File not found. Searched the following locations: \"\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/33/33cF1aA9541AdeBE6dAeFC3BcA342908b96C61e3_Controller.sol:150:1:\n    |\n150 | import \"../IERC20.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/extensions/draft-IERC20Permit.sol\" not found: File not found. Searched the following locations: \"\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/33/33cF1aA9541AdeBE6dAeFC3BcA342908b96C61e3_Controller.sol:151:1:\n    |\n151 | import \"../extensions/draft-IERC20Permit.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/utils/Address.sol\" not found: File not found. Searched the following locations: \"\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/33/33cF1aA9541AdeBE6dAeFC3BcA342908b96C61e3_Controller.sol:152:1:\n    |\n152 | import \"../../../utils/Address.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/33/utils/Interfaces.sol\" not found: File not found. Searched the following locations: \"\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/33/33cF1aA9541AdeBE6dAeFC3BcA342908b96C61e3_Controller.sol:488:1:\n    |\n488 | import \"./utils/Interfaces.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"@openzeppelin/contracts/token/ERC20/IERC20.sol\" not found: File not found. Searched the following locations: \"\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/33/33cF1aA9541AdeBE6dAeFC3BcA342908b96C61e3_Controller.sol:489:1:\n    |\n489 | import \"@openzeppelin/contracts/token/ERC20/IERC20.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/33/utils/MathUtil.sol\" not found: File not found. Searched the following locations: \"\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/33/33cF1aA9541AdeBE6dAeFC3BcA342908b96C61e3_Controller.sol:490:1:\n    |\n490 | import \"./utils/MathUtil.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol\" not found: File not found. Searched the following locations: \"\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/33/33cF1aA9541AdeBE6dAeFC3BcA342908b96C61e3_Controller.sol:491:1:\n    |\n491 | import \"@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"@openzeppelin/contracts/token/ERC20/IERC20.sol\" not found: File not found. Searched the following locations: \"\".\n    --> /Users/giacomoibba/Desktop/SmarthER/mainnet/33/33cF1aA9541AdeBE6dAeFC3BcA342908b96C61e3_Controller.sol:1020:1:\n     |\n1020 | import \"@openzeppelin/contracts/token/ERC20/IERC20.sol\";\n     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n", "results": {}}
