{"success": false, "error": "Traceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 544, in _run_solc\n    ret: Dict = json.loads(stdout)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 826, in main_impl\n    ) = process_all(filename, args, detector_classes, printer_classes)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 86, in process_all\n    compilations = compile_all(target, **vars(args))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 637, in compile_all\n    compilations.append(CryticCompile(target, **kwargs))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 117, in __init__\n    self._compile(**kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 548, in _compile\n    self._platform.compile(self, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 154, in compile\n    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 276, in _get_targets_json\n    return _run_solc(\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 548, in _run_solc\n    raise InvalidCompilation(f\"Invalid solc compilation {stderr}\")\ncrytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Multiple SPDX license identifiers found in source file. Use \"AND\" or \"OR\" to combine multiple licenses. Please see https://spdx.org for more information.\n--> /Users/giacomoibba/Desktop/mainnet/2a/2A24BB027d7fe2a62E39871187D644Daf03406f2_stkCvxCrvDistributorZaps.sol\n\nError: Source \"SafeERC20.sol\" not found: File not found.\n --> /Users/giacomoibba/Desktop/mainnet/2a/2A24BB027d7fe2a62E39871187D644Daf03406f2_stkCvxCrvDistributorZaps.sol:4:1:\n  |\n4 | import \"SafeERC20.sol\";\n  | ^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"DistributorZaps.sol\" not found: File not found.\n --> /Users/giacomoibba/Desktop/mainnet/2a/2A24BB027d7fe2a62E39871187D644Daf03406f2_stkCvxCrvDistributorZaps.sol:5:1:\n  |\n5 | import \"DistributorZaps.sol\";\n  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"IGenericVault.sol\" not found: File not found.\n --> /Users/giacomoibba/Desktop/mainnet/2a/2A24BB027d7fe2a62E39871187D644Daf03406f2_stkCvxCrvDistributorZaps.sol:6:1:\n  |\n6 | import \"IGenericVault.sol\";\n  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"IERC20.sol\" not found: File not found.\n  --> /Users/giacomoibba/Desktop/mainnet/2a/2A24BB027d7fe2a62E39871187D644Daf03406f2_stkCvxCrvDistributorZaps.sol:79:1:\n   |\n79 | import \"IERC20.sol\";\n   | ^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"Address.sol\" not found: File not found.\n  --> /Users/giacomoibba/Desktop/mainnet/2a/2A24BB027d7fe2a62E39871187D644Daf03406f2_stkCvxCrvDistributorZaps.sol:80:1:\n   |\n80 | import \"Address.sol\";\n   | ^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"SafeERC20.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/mainnet/2a/2A24BB027d7fe2a62E39871187D644Daf03406f2_stkCvxCrvDistributorZaps.sol:424:1:\n    |\n424 | import \"SafeERC20.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"IStrategyZaps.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/mainnet/2a/2A24BB027d7fe2a62E39871187D644Daf03406f2_stkCvxCrvDistributorZaps.sol:425:1:\n    |\n425 | import \"IStrategyZaps.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"IGenericDistributor.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/mainnet/2a/2A24BB027d7fe2a62E39871187D644Daf03406f2_stkCvxCrvDistributorZaps.sol:426:1:\n    |\n426 | import \"IGenericDistributor.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n", "results": {}}
