{"success": false, "error": "Traceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 544, in _run_solc\n    ret: Dict = json.loads(stdout)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 826, in main_impl\n    ) = process_all(filename, args, detector_classes, printer_classes)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 86, in process_all\n    compilations = compile_all(target, **vars(args))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 637, in compile_all\n    compilations.append(CryticCompile(target, **kwargs))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 117, in __init__\n    self._compile(**kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 548, in _compile\n    self._platform.compile(self, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 154, in compile\n    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 276, in _get_targets_json\n    return _run_solc(\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 548, in _run_solc\n    raise InvalidCompilation(f\"Invalid solc compilation {stderr}\")\ncrytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation /Users/giacomoibba/Desktop/mainnet/2a/2Ad83DECF0555945094E5D25129c1F324F212517_solidity_contracts_system_VendingMachine.sol:3:1: Error: Source \"openzeppelin-solidity/contracts/math/SafeMath.sol\" not found: File not found.\nimport {SafeMath} from \"openzeppelin-solidity/contracts/math/SafeMath.sol\";\n^-------------------------------------------------------------------------^\n/Users/giacomoibba/Desktop/mainnet/2a/2Ad83DECF0555945094E5D25129c1F324F212517_solidity_contracts_system_VendingMachine.sol:4:1: Error: Source \"/Users/giacomoibba/Desktop/mainnet/2a/TBTCDepositToken.sol\" not found: File not found.\nimport {TBTCDepositToken} from \"./TBTCDepositToken.sol\";\n^------------------------------------------------------^\n/Users/giacomoibba/Desktop/mainnet/2a/2Ad83DECF0555945094E5D25129c1F324F212517_solidity_contracts_system_VendingMachine.sol:5:1: Error: Source \"/Users/giacomoibba/Desktop/mainnet/2a/FeeRebateToken.sol\" not found: File not found.\nimport {FeeRebateToken} from \"./FeeRebateToken.sol\";\n^--------------------------------------------------^\n/Users/giacomoibba/Desktop/mainnet/2a/2Ad83DECF0555945094E5D25129c1F324F212517_solidity_contracts_system_VendingMachine.sol:6:1: Error: Source \"/Users/giacomoibba/Desktop/mainnet/2a/TBTCToken.sol\" not found: File not found.\nimport {TBTCToken} from \"./TBTCToken.sol\";\n^----------------------------------------^\n/Users/giacomoibba/Desktop/mainnet/2a/2Ad83DECF0555945094E5D25129c1F324F212517_solidity_contracts_system_VendingMachine.sol:7:1: Error: Source \"/Users/giacomoibba/Desktop/mainnet/2a/TBTCConstants.sol\" not found: File not found.\nimport {TBTCConstants} from \"./TBTCConstants.sol\";\n^------------------------------------------------^\n/Users/giacomoibba/Desktop/mainnet/2a/2Ad83DECF0555945094E5D25129c1F324F212517_solidity_contracts_system_VendingMachine.sol:8:1: Error: Source \"/Users/giacomoibba/Desktop/mainnet/deposit/Deposit.sol\" not found: File not found.\nimport \"../deposit/Deposit.sol\";\n^------------------------------^\n/Users/giacomoibba/Desktop/mainnet/2a/2Ad83DECF0555945094E5D25129c1F324F212517_solidity_contracts_system_VendingMachine.sol:9:1: Error: Source \"/Users/giacomoibba/Desktop/mainnet/2a/TBTCSystemAuthority.sol\" not found: File not found.\nimport \"./TBTCSystemAuthority.sol\";\n^---------------------------------^\n\n", "results": {}}
