{"success": false, "error": "Traceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 544, in _run_solc\n    ret: Dict = json.loads(stdout)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 826, in main_impl\n    ) = process_all(filename, args, detector_classes, printer_classes)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 86, in process_all\n    compilations = compile_all(target, **vars(args))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 637, in compile_all\n    compilations.append(CryticCompile(target, **kwargs))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 117, in __init__\n    self._compile(**kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 548, in _compile\n    self._platform.compile(self, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 154, in compile\n    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 276, in _get_targets_json\n    return _run_solc(\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 548, in _run_solc\n    raise InvalidCompilation(f\"Invalid solc compilation {stderr}\")\ncrytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Multiple SPDX license identifiers found in source file. Use \"AND\" or \"OR\" to combine multiple licenses. Please see https://spdx.org for more information.\n--> /Users/giacomoibba/Desktop/SmarthER/mainnet/d5/D58e1EAa15410275700E08754088490c4132Cc94_Autd.sol\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/Address.sol\" not found: File not found.\n --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d5/D58e1EAa15410275700E08754088490c4132Cc94_Autd.sol:6:1:\n  |\n6 | import \"../Address.sol\";\n  | ^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/d5/ISutd.sol\" not found: File not found.\n --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d5/D58e1EAa15410275700E08754088490c4132Cc94_Autd.sol:7:1:\n  |\n7 | import \"./ISutd.sol\";\n  | ^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/d5/IAutd.sol\" not found: File not found.\n --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d5/D58e1EAa15410275700E08754088490c4132Cc94_Autd.sol:8:1:\n  |\n8 | import \"./IAutd.sol\";\n  | ^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/ERC20/ERC20.sol\" not found: File not found.\n --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d5/D58e1EAa15410275700E08754088490c4132Cc94_Autd.sol:9:1:\n  |\n9 | import \"../ERC20/ERC20.sol\";\n  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/access-control/UnitedAccessControl.sol\" not found: File not found.\n  --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d5/D58e1EAa15410275700E08754088490c4132Cc94_Autd.sol:10:1:\n   |\n10 | import \"../access-control/UnitedAccessControl.sol\";\n   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/ERC20/IERC20.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d5/D58e1EAa15410275700E08754088490c4132Cc94_Autd.sol:552:1:\n    |\n552 | import \"../ERC20/IERC20.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/ERC20/IERC20.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d5/D58e1EAa15410275700E08754088490c4132Cc94_Autd.sol:589:1:\n    |\n589 | import \"../ERC20/IERC20.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/SafeMath.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d5/D58e1EAa15410275700E08754088490c4132Cc94_Autd.sol:610:1:\n    |\n610 | import \"../SafeMath.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/d5/IERC20.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d5/D58e1EAa15410275700E08754088490c4132Cc94_Autd.sol:612:1:\n    |\n612 | import \"./IERC20.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/authority/IUnitedAuthority.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d5/D58e1EAa15410275700E08754088490c4132Cc94_Autd.sol:739:1:\n    |\n739 | import \"../authority/IUnitedAuthority.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n", "results": {}}
