{"success": false, "error": "Traceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 544, in _run_solc\n    ret: Dict = json.loads(stdout)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 826, in main_impl\n    ) = process_all(filename, args, detector_classes, printer_classes)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 86, in process_all\n    compilations = compile_all(target, **vars(args))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 637, in compile_all\n    compilations.append(CryticCompile(target, **kwargs))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 117, in __init__\n    self._compile(**kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 548, in _compile\n    self._platform.compile(self, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 154, in compile\n    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 276, in _get_targets_json\n    return _run_solc(\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 548, in _run_solc\n    raise InvalidCompilation(f\"Invalid solc compilation {stderr}\")\ncrytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Multiple SPDX license identifiers found in source file. Use \"AND\" or \"OR\" to combine multiple licenses. Please see https://spdx.org for more information.\n--> /Users/giacomoibba/Desktop/SmarthER/mainnet/d2/D2A34731586bD10B645f870f4C9DcAF4F9e3823C_Liquidator.sol\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/tokens/ERC20.sol\" not found: File not found. Searched the following locations: \"\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d2/D2A34731586bD10B645f870f4C9DcAF4F9e3823C_Liquidator.sol:256:1:\n    |\n256 | import {ERC20} from \"../tokens/ERC20.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/d2/utils/LogExpMath.sol\" not found: File not found. Searched the following locations: \"\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d2/D2A34731586bD10B645f870f4C9DcAF4F9e3823C_Liquidator.sol:388:1:\n    |\n388 | import { LogExpMath } from \"./utils/LogExpMath.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/d2/interfaces/IFactory.sol\" not found: File not found. Searched the following locations: \"\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d2/D2A34731586bD10B645f870f4C9DcAF4F9e3823C_Liquidator.sol:389:1:\n    |\n389 | import { IFactory } from \"./interfaces/IFactory.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/lib/solmate/src/utils/SafeTransferLib.sol\" not found: File not found. Searched the following locations: \"\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d2/D2A34731586bD10B645f870f4C9DcAF4F9e3823C_Liquidator.sol:390:1:\n    |\n390 | import { ERC20, SafeTransferLib } from \"../lib/solmate/src/utils/SafeTransferLib.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/d2/interfaces/IVault.sol\" not found: File not found. Searched the following locations: \"\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d2/D2A34731586bD10B645f870f4C9DcAF4F9e3823C_Liquidator.sol:391:1:\n    |\n391 | import { IVault } from \"./interfaces/IVault.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/d2/interfaces/ILendingPool.sol\" not found: File not found. Searched the following locations: \"\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d2/D2A34731586bD10B645f870f4C9DcAF4F9e3823C_Liquidator.sol:392:1:\n    |\n392 | import { ILendingPool } from \"./interfaces/ILendingPool.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"lib/solmate/src/auth/Owned.sol\" not found: File not found. Searched the following locations: \"\".\n   --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d2/D2A34731586bD10B645f870f4C9DcAF4F9e3823C_Liquidator.sol:393:1:\n    |\n393 | import { Owned } from \"lib/solmate/src/auth/Owned.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/SmarthER/mainnet/d2/BalancerErrors.sol\" not found: File not found. Searched the following locations: \"\".\n    --> /Users/giacomoibba/Desktop/SmarthER/mainnet/d2/D2A34731586bD10B645f870f4C9DcAF4F9e3823C_Liquidator.sol:1127:1:\n     |\n1127 | import \"./BalancerErrors.sol\";\n     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n", "results": {}}
