{"success": false, "error": "Traceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 544, in _run_solc\n    ret: Dict = json.loads(stdout)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 826, in main_impl\n    ) = process_all(filename, args, detector_classes, printer_classes)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 86, in process_all\n    compilations = compile_all(target, **vars(args))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 637, in compile_all\n    compilations.append(CryticCompile(target, **kwargs))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 117, in __init__\n    self._compile(**kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 548, in _compile\n    self._platform.compile(self, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 154, in compile\n    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 276, in _get_targets_json\n    return _run_solc(\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 548, in _run_solc\n    raise InvalidCompilation(f\"Invalid solc compilation {stderr}\")\ncrytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Multiple SPDX license identifiers found in source file. Use \"AND\" or \"OR\" to combine multiple licenses. Please see https://spdx.org for more information.\n--> /Users/giacomoibba/Desktop/mainnet/2a/2Aa24DAc5E494e7B028ED43023530E5769df5D8b_UnderwriterToken.sol\n\nError: Source \"/Users/giacomoibba/Desktop/mainnet/utils/Context.sol\" not found: File not found.\n --> /Users/giacomoibba/Desktop/mainnet/2a/2Aa24DAc5E494e7B028ED43023530E5769df5D8b_UnderwriterToken.sol:5:1:\n  |\n5 | import \"../utils/Context.sol\";\n  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/mainnet/IERC20.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/mainnet/2a/2Aa24DAc5E494e7B028ED43023530E5769df5D8b_UnderwriterToken.sol:152:1:\n    |\n152 | import \"../IERC20.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"@openzeppelin/contracts/access/Ownable.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/mainnet/2a/2Aa24DAc5E494e7B028ED43023530E5769df5D8b_UnderwriterToken.sol:205:1:\n    |\n205 | import \"@openzeppelin/contracts/access/Ownable.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/mainnet/2a/IERC20WithPermit.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/mainnet/2a/2Aa24DAc5E494e7B028ED43023530E5769df5D8b_UnderwriterToken.sol:207:1:\n    |\n207 | import \"./IERC20WithPermit.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/mainnet/2a/IReceiveApproval.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/mainnet/2a/2Aa24DAc5E494e7B028ED43023530E5769df5D8b_UnderwriterToken.sol:208:1:\n    |\n208 | import \"./IReceiveApproval.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"@openzeppelin/contracts/token/ERC20/IERC20.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/mainnet/2a/2Aa24DAc5E494e7B028ED43023530E5769df5D8b_UnderwriterToken.sol:560:1:\n    |\n560 | import \"@openzeppelin/contracts/token/ERC20/IERC20.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/mainnet/2a/2Aa24DAc5E494e7B028ED43023530E5769df5D8b_UnderwriterToken.sol:561:1:\n    |\n561 | import \"@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/mainnet/2a/IApproveAndCall.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/mainnet/2a/2Aa24DAc5E494e7B028ED43023530E5769df5D8b_UnderwriterToken.sol:563:1:\n    |\n563 | import \"./IApproveAndCall.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"@thesis/solidity-contracts/contracts/token/ERC20WithPermit.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/mainnet/2a/2Aa24DAc5E494e7B028ED43023530E5769df5D8b_UnderwriterToken.sol:650:1:\n    |\n650 | import \"@thesis/solidity-contracts/contracts/token/ERC20WithPermit.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n", "results": {}}
