{"success": false, "error": "Traceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 544, in _run_solc\n    ret: Dict = json.loads(stdout)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 826, in main_impl\n    ) = process_all(filename, args, detector_classes, printer_classes)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/slither/__main__.py\", line 86, in process_all\n    compilations = compile_all(target, **vars(args))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 637, in compile_all\n    compilations.append(CryticCompile(target, **kwargs))\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 117, in __init__\n    self._compile(**kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 548, in _compile\n    self._platform.compile(self, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 154, in compile\n    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 276, in _get_targets_json\n    return _run_solc(\n  File \"/Users/giacomoibba/miniconda3/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 548, in _run_solc\n    raise InvalidCompilation(f\"Invalid solc compilation {stderr}\")\ncrytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Multiple SPDX license identifiers found in source file. Use \"AND\" or \"OR\" to combine multiple licenses. Please see https://spdx.org for more information.\n--> /Users/giacomoibba/Desktop/mainnet/2a/2Ac8172D8Ce1C5Ad3D869556FD708801a42c1c0E_EnvoyToken.sol\n\nError: Source \"@openzeppelin/contracts/access/AccessControl.sol\" not found: File not found.\n --> /Users/giacomoibba/Desktop/mainnet/2a/2Ac8172D8Ce1C5Ad3D869556FD708801a42c1c0E_EnvoyToken.sol:4:1:\n  |\n4 | import \"@openzeppelin/contracts/access/AccessControl.sol\";\n  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"@openzeppelin/contracts/utils/Context.sol\" not found: File not found.\n --> /Users/giacomoibba/Desktop/mainnet/2a/2Ac8172D8Ce1C5Ad3D869556FD708801a42c1c0E_EnvoyToken.sol:5:1:\n  |\n5 | import \"@openzeppelin/contracts/utils/Context.sol\";\n  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"@openzeppelin/contracts/token/ERC20/ERC20.sol\" not found: File not found.\n --> /Users/giacomoibba/Desktop/mainnet/2a/2Ac8172D8Ce1C5Ad3D869556FD708801a42c1c0E_EnvoyToken.sol:6:1:\n  |\n6 | import \"@openzeppelin/contracts/token/ERC20/ERC20.sol\";\n  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/mainnet/utils/Context.sol\" not found: File not found.\n  --> /Users/giacomoibba/Desktop/mainnet/2a/2Ac8172D8Ce1C5Ad3D869556FD708801a42c1c0E_EnvoyToken.sol:49:1:\n   |\n49 | import \"../utils/Context.sol\";\n   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/mainnet/utils/introspection/ERC165.sol\" not found: File not found.\n  --> /Users/giacomoibba/Desktop/mainnet/2a/2Ac8172D8Ce1C5Ad3D869556FD708801a42c1c0E_EnvoyToken.sol:50:1:\n   |\n50 | import \"../utils/introspection/ERC165.sol\";\n   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/mainnet/2a/IERC20.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/mainnet/2a/2Ac8172D8Ce1C5Ad3D869556FD708801a42c1c0E_EnvoyToken.sol:288:1:\n    |\n288 | import \"./IERC20.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/utils/Context.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/mainnet/2a/2Ac8172D8Ce1C5Ad3D869556FD708801a42c1c0E_EnvoyToken.sol:289:1:\n    |\n289 | import \"../../utils/Context.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nError: Source \"/Users/giacomoibba/Desktop/mainnet/2a/IERC165.sol\" not found: File not found.\n   --> /Users/giacomoibba/Desktop/mainnet/2a/2Ac8172D8Ce1C5Ad3D869556FD708801a42c1c0E_EnvoyToken.sol:592:1:\n    |\n592 | import \"./IERC165.sol\";\n    | ^^^^^^^^^^^^^^^^^^^^^^^\n\n\n", "results": {}}
